# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
#   schedule:
#   - cron: "0 2 1 * *"

jobs:
  build:
    name: ${{ matrix.os }} Java ${{ matrix.java }} ${{ matrix.javadist }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java: [11]
        javadist: ['adopt-openj11']
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Java ${{ matrix.java }} ${{ matrix.javadist }}
      uses: actions/setup-java@v2
      with:
        distribution: ${{ matrix.javadist }}
        java-version: ${{ matrix.java }}
       
    - name: Build with Maven
      run: mvn -B package --file test-systemds/pom.xml
      
